extends Node

enum DiceEnum { D4, D6, D8, D10, D12, D20 };
enum Upgrade { ADD_DICE, UPGRADE_DICE, DUNGEON_MASTER, DICE_TOWER, REROLL, DICE_TRAY, CONTRACT, ROLL_DECREASE, ASCEND };
enum LootType { CURRENCY, FEATHERS, DEMON_FEATHERS, BOLTS };
#Order is crucial in this enum do not move items around:
enum SaveFlag {
	CURRENCY,
	FEATHERS,
	BOLTS,
	DEMON_FEATHERS,
	
	U_ADD_DICE,
	U_UPGRADE_DICE,
	U_DUNGEON_MASTER,
	U_DICE_TOWER,
	U_REROLL,
	U_CONTRACT,
	
	DICE,
	TARGET_ENEMY_BEATEN,
	
	A_MULTIPLIER_VALUE,
	A_MULTIPLIER_LEVEL,
	A_REROLL_VALUE,
	A_REROLL_LEVEL,
	
	#TODO: Dice tower and add dice start level
#	AD_MULTIPLIER, # MULTIPLIER YES OR CANCEL?
	AD_UPGRADE_DICE,
	AD_CONTRACT,
	UD_UPGRADE_DICE
	UD_CONTRACT
}
